name: Demo CI env levels 

on:
  push 
  # workflow_dispatch
env:
  GLOBAL_APP_ENV: global-dev

jobs:
    build:
        runs-on: ubuntu-latest

        env:
          JOB_APP_ENV: job-dev

        steps:
          - name: Say Hello
            run: echo "Hello from the fourth workflow!"          
          
          - name: Create Demo file
            env:
              APP_ENV: dev 
            run: |
              echo "'Environment $APP_ENV' > demo.txt"
              echo "file created demo.txt"

          - name: Upload Demo 
            uses: actions/upload-artifact@v4
            with:
              name: build-actifacts-demo
              path: .