name: Demo CI env Secrets 

on:
  push 
  # workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - name: Say Hello
            run: echo 

          - name: Install
            env:
              APP_ENV: demo 
            run: echo "Environment $APP_ENV"